### PR TITLE
debug: debug RPC to view underpriced tx-fetcher state and util to clear

### PR DESCRIPTION
**Pull request by protolambda**
**Description**

Debug utils to review the tx-fetcher underpriced-txs state.

The issue is already fixed in upstream geth, in `v1.13.2`. This PR is based on an older op-geth version (`v1.101200.1`, based on upstream `v1.12.0`), to act in prior deployments where necessary.

- `debug_clearUnderpriced` to clear state
- `debug_listUnderpriced` to see tx-hashes that are considered too underpriced to refetch

### CODE REVIEW

**Review by Inphi — APPROVED** [review]

**Comment by Inphi** [comment]
Let's merge this in so we can cut a new release with this change.

**Comment by protolambda** [comment]
@Inphi I don't think we want to permanently include these changes, adopting v1.13.2 changes to include the timeout fix seems like a better long-term route.

**Comment by Inphi** [comment]
Ageeed. I'd like to merge this in soon though so the next op-geth release contains it. Otherwise release management would get complicated.

We can revert this change once the proper upstream fix is merged. I doubt anyone else will miss having these debug RPCs.

**Comment by protolambda** [comment]
Actually, I think the interface check won't work, I need to make a change to the backend to route the interface call to the `Ethereum` struct, will update.

**Comment by Inphi** [comment]
Aye. Will check on devnet.

**Review by Inphi — APPROVED** [review]
underpriced list shows up as an empty list now rather than null:
```
$ cast rpc debug_listUnderpriced
[]
```

**Comment by ajsutton** [comment]
@Inphi @protolambda Seems like we resolved not to merge this, so should we close it?

**Comment by Inphi** [comment]
yup we can close.

**Pull request closed without merging**
