### PR TITLE
Update to geth v1.11.5 (erszbat)

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

Merges in changes from latest geth release (v1.11.5 - erszbat).

**Metadata**
- https://linear.app/optimism/issue/CLI-3692/update-to-geth-1115

### CODE REVIEW

**Comment by ajsutton** [comment]
Have confirmed op-e2e tests all pass using this new version and it can successfully sync part of the Goerli chain.

**Comment by ajsutton** [comment]
Worth noting this op-geth specific commit: https://github.com/ethereum-optimism/op-geth/pull/74/commits/876919e42d47946d946fe3f654156b14f7c682d1

It maintains a fix from the upgrade to v1.11.4 - upstream geth no longer supports `safe` or `finalised` tags if there hasn't yet been a call to `engine_forkChoiceUpdated` which it uses as the signal that TTD is reached. That causes issues in our e2e test setup at minimum and is generally not a great option given all bedrock networks are post-merge.

**Comment by protolambda** [comment]
Update:
- looking into running `merger.FinalizePoS()` on startup if the optimism config is there, to avoid relying on a first engine API method call, so it's merged from genesis. That way we don't have to remove the merge-dependent checks elsewhere, and can revert 876919e42d47946d946fe3f654156b14f7c682d1
- working on testing in op-e2e and goerli

**Comment by protolambda** [comment]
Bedrock is post-PoS, and needs the `FinalizePoS()` to function as expected on fresh networks starting from genesis.

I fixed our op-e2e test setup to use a fake Proof-of-stake block building loop instead of using Clique. We used to mock finalized/safe head changes on clique, but if upstream geth does not want to support safe/finalized labels for pre-PoS networks then I think we should just stop using Clique for testing.

Note that attaching to Clique networks outside of op-e2e would still work, but those don't have finalized data, and will never have, so the L2 won't get finalized either there.

See https://github.com/ethereum-optimism/optimism/pull/5225

**Comment by ajsutton** [comment]
Yeah that's a much nicer solution and brings us much more into line with geth's design and expectations. Thanks.

**Pull request merged**
