### PR TITLE
setting up CODEOWNERS

### PR DESCRIPTION
**Pull request by raffaele-oplabs**
**Description**

setting up CODEOWNERS

**Tests**

setting up CODEOWNERS

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Review by sebastianst — DISMISSED** [review]

**Review by sebastianst — COMMENTED** [review]
LGTM, but would be great to also add an entry for this to the [fork.yaml](https://github.com/ethereum-optimism/op-geth/blob/optimism/fork.yaml) file. For reference, this is the output that is generated from this: https://op-geth.optimism.io/

**Comment by raffaele-oplabs** [comment]
@sebastianst shall I add this at the end of the file in the ignore section? https://github.com/ethereum-optimism/op-geth/blob/0402d543c3d0cff3a3d344c0f4f83809edb44f10/fork.yaml#L260

**Comment by sebastianst** [comment]
@raffaele-oplabs yes, but let's actually just widen the ignore of `  - ".github/workflows/*"` to `  - ".github/*"`. We don't need to track anything inside `.github`.

**Review by sebastianst — APPROVED** [review]
LGTM

**Pull request merged**
