### PR TITLE
op-geth: more daisychain routing

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Adds the following RPC endpoints to the daisychain usage:

- `eth_getBalance`
- `eth_getProof`
- `eth_getCode`
- `eth_getStorageAt`
- `eth_getTransactionCount`

Closes ENG-3203

### CODE REVIEW

**Comment by trianglesphere** [comment]
LGTM pending testing

**Comment by mslipper** [comment]
I tested this. Pushed a commit to address issues. LGTM. @tynes please review my diff, and merge if it's OK with you.

**Review by mslipper — APPROVED** [review]

**Comment by tynes** [comment]
Changes look good to me, thank you for testing. Altho not sure why the other approach wasn't working :thinking: It looks basically the same except 2 calls to the backend instead of 1

**Comment by tynes** [comment]
Hmm there is a failing test now

```
--- FAIL: TestEthClient (0.12s)
    --- FAIL: TestEthClient/BalanceAt (0.00s)
        --- FAIL: TestEthClient/BalanceAt/future_block (0.00s)
            ethclient_test.go:472: BalanceAt(71562b71999873db5b286df957af199ec94617f7, 1000000000) error = %!q(<nil>), want "header not found"
```

**Comment by mslipper** [comment]
Before it was checking the header and state all at once, so it triggered the error case in the if and never executed the call to the historical endpoint.

**Pull request merged**
