### PR TITLE
miner: Account for L1 Info Deposit gas usage in the pending pool

### PR DESCRIPTION
**Pull request by trianglesphere**
**Description**
L1 Info Gas Overhead is the amount of gas the the L1 info deposit consumes. It is removed from the `pool.currentMaxGas` variable to ensure that transactions that use lots of gas are properly rejected. This is done in the transaction pool because while the block gas limit is typically the same, every L2 block contains a L1 info deposit which takes 60k-70k gas. This means that if a L2 tx tries to use the full block gas limit, it will enter the mempool, but never get included. This provides an early rejection.
**Tests**

Tests are in https://github.com/ethereum-optimism/optimism/pull/5496

**Metadata**

- Fixes CLI-3840

### CODE REVIEW

**Comment by trianglesphere** [comment]
@ajsutton I added a test & modified to to change `pool.currentMaxGas` like you suggested. I go confused between the `pendingBlock` code and the txpool code. We want to modify the txpool code in this case to reject overly large transactions.

Thinking about this a bit more, we will always need something like this because we could start including the deposits in the pending block which would make estimation more realistic, but we use this code for gas limit validity.

**Review by ajsutton — APPROVED** [review]
LGTM.

The TX pool is _so close_ to being able to find the amount to subtract automatically since it's getting the gas limit from the chain head block already - it could just subtract the gas used by the first transaction in that block and it would be an accurate measure of the gas actually used.  But it only has the header not the full block. :(

**Comment by trianglesphere** [comment]
> The TX pool is _so close_ to being able to find the amount to subtract automatically since it's getting the gas limit from the chain head block already - it could just subtract the gas used by the first transaction in that block and it would be an accurate measure of the gas actually used. But it only has the header not the full block. :(

Yea it's close. One tricky thing is that the gas used by the L1 info tx can vary so it becomes tricky if there is an abnormally low gas used by a specific L1 info deposit.

**Comment by ajsutton** [comment]
> Yea it's close. One tricky thing is that the gas used by the L1 info tx can vary so it becomes tricky if there is an abnormally low gas used by a specific L1 info deposit.

I think this is fine actually. If it's possible for the L1 info tx to use a small amount of info eventually it should do so again allowing the large TX to fit into the block. It's not really much different to a transaction on L1 that uses nearly all the block gas limit - unless it has a high gas price to make it the first tx to go into the block, it will wind up not fitting.  The txpool re-evaluates transactions regularly based on the latest block so it will wind up pruning out anything that is too close to the limit. The slightly more annoying thing would be if the L1 info tx uses more gas than normal the tx pool may prune a transaction that would have fit into the next block but we'd probably prune it with this fixed limit anyway.

**Pull request merged**
