### PR TITLE
Update geth to Vana (v1.11.4)

### PR DESCRIPTION
**Pull request by protolambda**
**Description**

Only a few weeks of upstream geth changes, but some pretty breaking API changes:
- `core.Message` interface doesn't exist anymore. It's a struct now.
  - Our L1 cost function now takes args, instead of getting them from the optimism specific subset of the message interface subset
  - The state transition adopted this `Message` struct, which now also includes the additonal (and optional) optimism fields.
  - This refactor upstream was partially motivated by 4844 I believe, due to data-gas refactoring required there.
  - Some of that code they changed was from 2014 (!!!)
- The transaction pool handles replacements with cost different (see DoS notes in their recent v1.11.x releases)
  - Had to update this to also include the L1-cost component of the transactions
- The simulated backend API was affected by interface changes; I had to resolve some merge conflicts there since we extended this a lot already.
- Chain markers changed from block to header, breaking a few minor things
- The "effective gas price" receipt meta-data is now derived during the receipt-hydration thing, instead of in the API util function. This also includes the addition of a method on the transaction inner types, to do type-specific computation of the effective gas price.
  - I'm currently setting the effective gas price in the receipt to 0. Since technically we don't charge the gas on L2, but on L1, so the gas-price is effectively 0. Previously the regular gas-price would be 0 in the deposit tx data, but wrongly be non-zero and reflect the real tx gas cost. We can preserve this behavior, but I think it was incorrect anyway. cc @K-Ho 

*Work in progress*: resolved all merge conflicts, but need to test against the monorepo op-e2e and draft the changes to land this there (some of the API changes like `core.Message` probably affect some testing and/or tooling).

Fix CLI-3611

### CODE REVIEW

**Comment by ajsutton** [comment]
Ok, first issue was simple - we just weren't providing any gas for deposit tx to run.  The assignment to `st.gas` in `preCheck` got lost (now it's an assignment to `st.gasRemaining` - just assigning to `st.initialGas` isn't enough).

Second issue is that it's incorrectly calculating contract addresses in regolith. It's using 0 for nonce again somehow. Will dig more...

**Comment by ajsutton** [comment]
Second issue was just a bad merge - the `ContractAddress` was set correctly but then overridden on the next line by the original geth code that used the tx nonce instead of the deposit nonce.

All the `op_geth_test` tests are now passing.  System tests are crashing because of a `nil` dereference when handling a `eth_getBlockByNumber` request for the `finalized` block.  That turns out to be a bug in the upstream geth (very easy to reproduce). Should be easy to fix  but will spend a bit of time auditing other places where the finalised block header is retrieved (previously the finalised block) and see if there are similar bugs.

**Comment by ajsutton** [comment]
Upstream geth has fixed it, but not in a way that works with op-node. Latest builds of geth will return an error if you request `safe` or `finalized` when `!b.eth.Merger().TDDReached()` which our system tests are hitting. That's also a breaking change in API behaviour so probably need to follow up with the geth team about it since it used to just return `nil` which got translated to a not found response.  For now I've stuck with my fix to return nil/not found.

Also found a lot more places the API changes broke e2e tests - go just apparently wasn't attempting to compile them before. 

`TestBigL2Txs` is apparently spending so much money sending transactions the account runs out of funds. The new tx pool validations are kicking in and preventing the batcher from submitting more transactions. I can make it pass by increasing the initial balance given to test users. From my understanding it's using the stub batcher and actually testing the op-node derivation so working around it like that is reasonable. I think the tx can be fit into blocks because then they only pay for the actual gas cost instead of the maximum possible cost.

Anyway with the fixes pushed here plus https://github.com/ethereum-optimism/optimism/pull/5185 all the e2e tests are now passing.

**Comment by protolambda** [comment]
Test status:
- Tested Goerli syncing around genesis
- Tested Goerli syncing around tip of chain
- Tested/Updated monorepo (op-e2e etc.) - with https://github.com/ethereum-optimism/optimism/pull/5185

Merging now.

**Pull request merged**
